# Generated by Django 5.1.2 on 2024-10-25 19:48

from django.db import migrations, models

from socialmedia import settings


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_followers_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
