# Generated by Django 5.1.2 on 2024-10-25 20:05

from django.db import migrations, models

from socialmedia import settings


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_profile_activation_token_profile_is_active'),



    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
